apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fc0702wu0-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5fc8b932c41014046fbd9bddb318fa097f58caf2@sha256:d269babae048d994d4a1fa32e4c6d745ecc038b39ba7731e4926c28dcdd4ad4a
          name: container-image
